/**
 * Paralegals — single source of truth for the licensed paralegals at the firm.
 *
 * Each entry is used wherever a document is generated on behalf of a paralegal
 * (retainers, demand letters, motion records, email signatures, etc.) and
 * drives the auto-populated signature block, printed name, LSO licence
 * number and credential line.
 *
 * For the moment this is a hardcoded list. If the firm grows or you'd rather
 * edit paralegals from the Wix admin without redeploying, this can be moved
 * to a Wix data collection ("paralegals") and loaded async — every consumer
 * already calls through `getActiveParalegals()` / `getParalegalById()` so the
 * change becomes a single-file refactor.
 */

import { EMAIL_PRIMARY, PHONE_DISPLAY } from './contact';

export interface Paralegal {
  /** Stable identifier (use lowercase, kebab-case). */
  id: string;
  /** Full display name as it appears on signed documents. */
  displayName: string;
  /** First name only — useful for greetings, email signatures. */
  firstName: string;
  /** Last name only. */
  lastName: string;
  /** LSO licence number, e.g. "P22020". */
  lsoNumber: string;
  /**
   * Electronic-signature text rendered on signed documents using the legal
   * convention `/s/ <Name>`. Equivalent to a wet signature for the purpose
   * of paralegal-prepared retainers and correspondence.
   */
  electronicSignatureText: string;
  /** Email used as the document author / from-address. */
  email: string;
  /** Phone number shown on the signature block. */
  phone: string;
  /** Credential line under the signature, e.g. "Licensed Paralegal". */
  credentialLine: string;
  /** Whether this paralegal is currently active and selectable in the UI. */
  active: boolean;
}

// ============================================================
// SEED DATA
// ============================================================

export const PARALEGALS: Paralegal[] = [
  {
    id: 'jeanfrancois-demers',
    displayName: 'Jean-Francois Demers',
    firstName: 'Jean-Francois',
    lastName: 'Demers',
    lsoNumber: 'P22020',
    electronicSignatureText: '/s/ Jean-Francois Demers',
    email: EMAIL_PRIMARY,
    phone: PHONE_DISPLAY,
    credentialLine: 'Licensed Paralegal, Law Society of Ontario',
    active: true,
  },
  {
    id: 'candice-fogarty',
    displayName: 'Candice Fogarty',
    firstName: 'Candice',
    lastName: 'Fogarty',
    lsoNumber: 'P21479',
    electronicSignatureText: '/s/ Candice Fogarty',
    email: EMAIL_PRIMARY,
    phone: PHONE_DISPLAY,
    credentialLine: 'Licensed Paralegal, Law Society of Ontario',
    active: true,
  },
];

// ============================================================
// HELPERS
// ============================================================

/**
 * Returns all currently-active paralegals, suitable for populating a
 * "Generated by" dropdown on document-generation forms.
 */
export function getActiveParalegals(): Paralegal[] {
  return PARALEGALS.filter((p) => p.active);
}

/**
 * Find a paralegal by id. Returns `undefined` if no match (callers should
 * fall back to a sensible default — usually the firm's primary paralegal).
 */
export function getParalegalById(id: string | null | undefined): Paralegal | undefined {
  if (!id) return undefined;
  return PARALEGALS.find((p) => p.id === id);
}

/**
 * The default paralegal selected when the form first loads (firm primary).
 * Falls back to the first active paralegal in the list if the primary id
 * isn't found.
 */
export const DEFAULT_PARALEGAL_ID = 'jeanfrancois-demers';

export function getDefaultParalegal(): Paralegal {
  return (
    getParalegalById(DEFAULT_PARALEGAL_ID) ||
    getActiveParalegals()[0] ||
    PARALEGALS[0]
  );
}

/**
 * Best-effort match of an authenticated user to one of our paralegals.
 *
 * Used to pre-select the "Generated by" dropdown to whichever paralegal is
 * currently logged in. Matches in this order:
 *   1. Exact email match
 *   2. Display name contains last name
 *   3. Falls back to the firm default
 */
export function resolveLoggedInParalegal(authUser: {
  email?: string | null;
  name?: string | null;
} | null | undefined): Paralegal {
  if (authUser) {
    if (authUser.email) {
      const byEmail = PARALEGALS.find(
        (p) => p.email.toLowerCase() === authUser.email!.toLowerCase()
      );
      if (byEmail) return byEmail;
    }
    if (authUser.name) {
      const lower = authUser.name.toLowerCase();
      const byName = PARALEGALS.find((p) => lower.includes(p.lastName.toLowerCase()));
      if (byName) return byName;
    }
  }
  return getDefaultParalegal();
}
