/**
 * Document Generation and Signature Embedding Utility
 * 
 * This utility provides functions to:
 * 1. Generate PDF documents from content
 * 2. Embed electronic signatures with metadata (date, time, IP) into documents
 * 
 * Uses HTML-to-PDF conversion for client-side PDF generation.
 */

import { SignatureData } from '@/components/DocumentSignature';

/**
 * Generates a PDF document from content
 * @param content - The text content to convert to PDF
 * @param documentName - Name of the document
 * @returns Base64 encoded PDF data URL
 */
export async function generatePDF(content: string, documentName: string): Promise<string> {
  const documentId = `DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  const generatedDate = new Date().toLocaleString();

  // Check if content is HTML or plain text
  const isHtmlContent = content.trim().startsWith('<') || 
                        /<[a-z][\s\S]*>/i.test(content);

  // Create HTML content for PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    .header {
      text-align: center;
      border-bottom: 3px double #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 18pt;
      font-weight: bold;
      margin: 0 0 10px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .header .meta {
      font-size: 10pt;
      color: #555;
    }
    .content {
      margin: 30px 0;
      text-align: justify;
    }
    .content.plain-text {
      white-space: pre-wrap;
    }
    /* HTML content styling */
    .content h1 {
      font-size: 16pt;
      font-weight: bold;
      margin: 20px 0 10px 0;
    }
    .content h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 18px 0 8px 0;
    }
    .content h3 {
      font-size: 13pt;
      font-weight: bold;
      margin: 16px 0 6px 0;
    }
    .content p {
      margin: 10px 0;
    }
    .content ul, .content ol {
      margin: 10px 0;
      padding-left: 30px;
    }
    .content li {
      margin: 5px 0;
    }
    .content table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    .content table th,
    .content table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }
    .content table th {
      background-color: #f0f0f0;
      font-weight: bold;
    }
    .content strong {
      font-weight: bold;
    }
    .content em {
      font-style: italic;
    }
    .content u {
      text-decoration: underline;
    }
    .content hr {
      border: none;
      border-top: 1px solid #000;
      margin: 20px 0;
    }
    .signature-section {
      margin-top: 60px;
      border-top: 2px solid #000;
      padding-top: 30px;
    }
    .signature-section h2 {
      font-size: 14pt;
      font-weight: bold;
      margin-bottom: 20px;
    }
    .signature-line {
      margin-top: 60px;
      border-top: 1px solid #000;
      width: 300px;
      padding-top: 5px;
      font-size: 10pt;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    .document-id {
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(documentName)}</h1>
    <div class="meta">Generated: ${generatedDate}</div>
  </div>

  <div class="content${isHtmlContent ? '' : ' plain-text'}">
${isHtmlContent ? content : escapeHtml(content)}
  </div>

  <div class="signature-section">
    <h2>Signature Section</h2>
    <p>This document requires your electronic signature. Please sign using the document workflow portal.</p>
    <div class="signature-line">
      Signature: {SIGNATURE_SECTION}
    </div>
    <p style="font-size: 9pt; color: #666; margin-top: 20px; font-style: italic;">
      Note: To have the signature replace a specific location in your template, add the placeholder 
      <strong>{SIGNATURE_SECTION}</strong>, <strong>{SIGNATURE}</strong>, or <strong>{{SIGNATURE}}</strong> 
      where you want the signature to appear in your template content.
    </p>
  </div>

  <div class="footer">
    <div class="document-id">Document ID: ${documentId}</div>
    <div>Generated by: Legal Services Document Workflow System</div>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF using browser's print functionality
  const pdfDataUrl = await htmlToPDF(htmlContent);
  
  return pdfDataUrl;
}

/**
 * Embeds signature with metadata into a PDF document
 * @param originalDocDataUrl - The original document as a data URL
 * @param signatureData - Signature data including image, date, time, and IP
 * @param documentName - Name of the document
 * @returns Base64 encoded signed PDF data URL
 */
export async function embedSignatureInPDF(
  originalDocDataUrl: string,
  signatureData: SignatureData,
  documentName: string
): Promise<string> {
  const documentId = `DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  const signedDate = new Date().toISOString();

  // Extract the original document content from the data URL
  let originalContent = '';
  
  try {
    if (originalDocDataUrl.startsWith('data:text/html;base64,')) {
      const base64Content = originalDocDataUrl.split(',')[1];
      const decodedContent = decodeURIComponent(escape(atob(base64Content)));
      
      // Parse the original HTML to extract just the content section
      const parser = new DOMParser();
      const doc = parser.parseFromString(decodedContent, 'text/html');
      const contentDiv = doc.querySelector('.content');
      
      if (contentDiv) {
        originalContent = contentDiv.innerHTML;
      } else {
        // Fallback: extract body content if .content div not found
        const bodyContent = doc.querySelector('body');
        if (bodyContent) {
          originalContent = bodyContent.innerHTML;
        }
      }
    }
  } catch (error) {
    console.error('Error extracting original document content:', error);
    originalContent = '<p>Original document content could not be extracted.</p>';
  }

  // Define signature placeholders in order of priority
  const placeholders = ['{SIGNATURE_SECTION}', '{SIGNATURE}', '{{SIGNATURE}}'];
  
  // Find the first placeholder that exists in the template
  let foundPlaceholder = null;
  for (const placeholder of placeholders) {
    if (originalContent.includes(placeholder)) {
      foundPlaceholder = placeholder;
      break;
    }
  }

  // Create verification details with preserved line breaks using <pre> tag
  const verificationDetails = `Date: ${escapeHtml(signatureData.signedDate)}
Time: ${escapeHtml(signatureData.signedTime)}
IP Address: ${escapeHtml(signatureData.ipAddress)}
Timestamp: ${signatureData.timestamp.toISOString()}`;

  // Create the signature HTML block with <pre> for verification details
  const signatureBlock = `
    <div class="signature-section">
      <h2>Electronic Signature</h2>
      
      <div class="signature-image">
        <img src="${signatureData.signatureDataUrl}" alt="Electronic Signature" />
        <div style="margin-top: 10px; font-size: 10pt;">Electronically Signed</div>
      </div>

      <div class="signature-details">
        <h3>Signature Verification Details</h3>
        <pre style="white-space: pre-wrap; font-family: monospace; font-size: 12px; line-height: 1.35; word-break: break-word; margin: 0; padding: 15px; background: white; border: 1px solid #ddd;">${verificationDetails}</pre>
      </div>

      <div class="certification">
        <strong>CERTIFICATION:</strong><br>
        This document has been electronically signed. The signature, date, time, and 
        IP address have been permanently affixed to this document and cannot be altered.
      </div>
    </div>
  `;

  // Replace signature placeholder if found, otherwise append at the end
  let finalContent;
  if (foundPlaceholder) {
    // Replace ONLY the first occurrence of the found placeholder
    finalContent = originalContent.replace(foundPlaceholder, signatureBlock);
  } else {
    // Append signature at the end if no placeholder found
    finalContent = originalContent + signatureBlock;
  }

  // Create HTML content for signed PDF with original content + signature
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    .header {
      text-align: center;
      border-bottom: 3px double #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 18pt;
      font-weight: bold;
      margin: 0 0 10px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .header .status {
      display: inline-block;
      background: #28a745;
      color: white;
      padding: 5px 15px;
      border-radius: 4px;
      font-size: 10pt;
      font-weight: bold;
      margin-top: 10px;
    }
    .content {
      margin: 30px 0;
      text-align: justify;
    }
    .content.plain-text {
      white-space: pre-wrap;
    }
    /* HTML content styling */
    .content h1 {
      font-size: 16pt;
      font-weight: bold;
      margin: 20px 0 10px 0;
    }
    .content h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 18px 0 8px 0;
    }
    .content h3 {
      font-size: 13pt;
      font-weight: bold;
      margin: 16px 0 6px 0;
    }
    .content p {
      margin: 10px 0;
    }
    .content ul, .content ol {
      margin: 10px 0;
      padding-left: 30px;
    }
    .content li {
      margin: 5px 0;
    }
    .content table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    .content table th,
    .content table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }
    .content table th {
      background-color: #f0f0f0;
      font-weight: bold;
    }
    .content strong {
      font-weight: bold;
    }
    .content em {
      font-style: italic;
    }
    .content u {
      text-decoration: underline;
    }
    .content hr {
      border: none;
      border-top: 1px solid #000;
      margin: 20px 0;
    }
    .signature-section {
      margin-top: 60px;
      border: 2px solid #000;
      padding: 30px;
      background: #f9f9f9;
      page-break-before: avoid;
    }
    .signature-section h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 0 0 20px 0;
      text-align: center;
      text-transform: uppercase;
    }
    .signature-image {
      text-align: center;
      margin: 20px 0;
      padding: 20px;
      background: white;
      border: 1px solid #ccc;
    }
    .signature-image img {
      max-width: 300px;
      max-height: 100px;
      border-bottom: 2px solid #000;
    }
    .signature-details {
      margin-top: 30px;
      border: 1px solid #000;
      padding: 20px;
      background: white;
    }
    .signature-details h3 {
      font-size: 12pt;
      font-weight: bold;
      margin: 0 0 15px 0;
      text-align: center;
      background: #000;
      color: white;
      padding: 10px;
    }
    .signature-details pre {
      white-space: pre-wrap;
      font-family: monospace;
      font-size: 12px;
      line-height: 1.35;
      word-break: break-word;
      margin: 0;
      padding: 15px;
      background: white;
      border: 1px solid #ddd;
    }
    .certification {
      margin-top: 30px;
      padding: 20px;
      background: #fffbcc;
      border: 2px solid #ffcc00;
      border-radius: 4px;
      font-size: 10pt;
      text-align: center;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    .document-id {
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(documentName)}</h1>
    <div class="status">✓ ELECTRONICALLY SIGNED</div>
  </div>

  <div class="content">
${finalContent}
  </div>

  <div class="footer">
    <div class="document-id">Document ID: ${documentId}</div>
    <div>Signed: ${signedDate}</div>
    <div>System: Legal Services Document Workflow System</div>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF
  const signedPdfDataUrl = await htmlToPDF(htmlContent);
  
  return signedPdfDataUrl;
}

/**
 * Converts a data URL to a Blob for downloading
 * @param dataUrl - The data URL to convert
 * @param filename - The filename for the download
 */
export function downloadPDF(dataUrl: string, filename: string): void {
  // Ensure filename has .html extension for HTML-based documents
  const finalFilename = filename.endsWith('.html') || filename.endsWith('.pdf') 
    ? filename 
    : `${filename}.html`;
  
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = finalFilename;
  link.target = '_blank';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Validates if a string is a valid PDF or HTML data URL
 * @param dataUrl - The data URL to validate
 * @returns True if valid document data URL
 */
export function isValidPDFDataUrl(dataUrl: string): boolean {
  return dataUrl.startsWith('data:application/pdf;base64,') || 
         dataUrl.startsWith('data:text/html;base64,');
}

/**
 * Helper function to escape HTML special characters
 * @param text - Text to escape
 * @returns Escaped text
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Converts HTML content to PDF data URL using browser's print functionality
 * @param htmlContent - HTML content to convert
 * @returns Base64 encoded PDF data URL (HTML format for viewing)
 */
async function htmlToPDF(htmlContent: string): Promise<string> {
  return new Promise((resolve) => {
    // Create a blob URL for the HTML content that can be viewed in browser
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const blobUrl = URL.createObjectURL(blob);
    
    // For better compatibility, we'll return the HTML as a data URL
    // This allows the document to be viewed in the browser and printed as PDF
    const base64Content = btoa(unescape(encodeURIComponent(htmlContent)));
    const htmlDataUrl = `data:text/html;base64,${base64Content}`;
    
    resolve(htmlDataUrl);
  });
}
