/**
 * Document Generation and Signature Embedding Utility
 * 
 * This utility provides functions to:
 * 1. Generate PDF documents from content
 * 2. Embed electronic signatures with metadata (date, time, IP) into documents
 * 
 * Uses HTML-to-PDF conversion for client-side PDF generation.
 */

import { SignatureData } from '@/components/DocumentSignature';

/**
 * Generates a PDF document from content
 * @param content - The text content to convert to PDF
 * @param documentName - Name of the document
 * @returns Base64 encoded PDF data URL
 */
export async function generatePDF(content: string, documentName: string): Promise<string> {
  const documentId = `DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  const generatedDate = new Date().toLocaleString();

  // Check if content is HTML or plain text
  const isHtmlContent = content.trim().startsWith('<') || 
                        /<[a-z][\s\S]*>/i.test(content);

  // Create HTML content for PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    .header {
      text-align: center;
      border-bottom: 3px double #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 18pt;
      font-weight: bold;
      margin: 0 0 10px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .header .meta {
      font-size: 10pt;
      color: #555;
    }
    .content {
      margin: 30px 0;
      text-align: justify;
    }
    .content.plain-text {
      white-space: pre-wrap;
    }
    /* HTML content styling */
    .content h1 {
      font-size: 16pt;
      font-weight: bold;
      margin: 20px 0 10px 0;
    }
    .content h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 18px 0 8px 0;
    }
    .content h3 {
      font-size: 13pt;
      font-weight: bold;
      margin: 16px 0 6px 0;
    }
    .content p {
      margin: 10px 0;
    }
    .content ul, .content ol {
      margin: 10px 0;
      padding-left: 30px;
    }
    .content li {
      margin: 5px 0;
    }
    .content table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    .content table th,
    .content table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }
    .content table th {
      background-color: #f0f0f0;
      font-weight: bold;
    }
    .content strong {
      font-weight: bold;
    }
    .content em {
      font-style: italic;
    }
    .content u {
      text-decoration: underline;
    }
    .content hr {
      border: none;
      border-top: 1px solid #000;
      margin: 20px 0;
    }
    .signature-section {
      margin-top: 60px;
      border-top: 2px solid #000;
      padding-top: 30px;
    }
    .signature-section h2 {
      font-size: 14pt;
      font-weight: bold;
      margin-bottom: 20px;
    }
    .signature-line {
      margin-top: 60px;
      border-top: 1px solid #000;
      width: 300px;
      padding-top: 5px;
      font-size: 10pt;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    .document-id {
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(documentName)}</h1>
    <div class="meta">Generated: ${generatedDate}</div>
  </div>

  <div class="content${isHtmlContent ? '' : ' plain-text'}">
${isHtmlContent ? content : escapeHtml(content)}
  </div>

  <div class="signature-section">
    <h2>Signature Section</h2>
    <p>This document requires your electronic signature. Please sign using the document workflow portal.</p>
    <div class="signature-line">
      Signature
    </div>
  </div>

  <div class="footer">
    <div class="document-id">Document ID: ${documentId}</div>
    <div>Generated by: Legal Services Document Workflow System</div>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF using browser's print functionality
  const pdfDataUrl = await htmlToPDF(htmlContent);
  
  return pdfDataUrl;
}

/**
 * Embeds signature with metadata into a PDF document
 * @param originalDocDataUrl - The original document as a data URL
 * @param signatureData - Signature data including image, date, time, and IP
 * @param documentName - Name of the document
 * @returns Base64 encoded signed PDF data URL
 */
export async function embedSignatureInPDF(
  originalDocDataUrl: string,
  signatureData: SignatureData,
  documentName: string
): Promise<string> {
  const documentId = `DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  const signedDate = new Date().toISOString();

  // Create HTML content for signed PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    .header {
      text-align: center;
      border-bottom: 3px double #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 18pt;
      font-weight: bold;
      margin: 0 0 10px 0;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .header .status {
      display: inline-block;
      background: #28a745;
      color: white;
      padding: 5px 15px;
      border-radius: 4px;
      font-size: 10pt;
      font-weight: bold;
      margin-top: 10px;
    }
    .signature-section {
      margin-top: 60px;
      border: 2px solid #000;
      padding: 30px;
      background: #f9f9f9;
    }
    .signature-section h2 {
      font-size: 14pt;
      font-weight: bold;
      margin: 0 0 20px 0;
      text-align: center;
      text-transform: uppercase;
    }
    .signature-image {
      text-align: center;
      margin: 20px 0;
      padding: 20px;
      background: white;
      border: 1px solid #ccc;
    }
    .signature-image img {
      max-width: 300px;
      max-height: 100px;
      border-bottom: 2px solid #000;
    }
    .signature-details {
      margin-top: 30px;
      border: 1px solid #000;
      padding: 20px;
      background: white;
    }
    .signature-details h3 {
      font-size: 12pt;
      font-weight: bold;
      margin: 0 0 15px 0;
      text-align: center;
      background: #000;
      color: white;
      padding: 10px;
    }
    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #eee;
    }
    .detail-label {
      font-weight: bold;
      width: 40%;
    }
    .detail-value {
      width: 60%;
      font-family: 'Courier New', monospace;
    }
    .certification {
      margin-top: 30px;
      padding: 20px;
      background: #fffbcc;
      border: 2px solid #ffcc00;
      border-radius: 4px;
      font-size: 10pt;
      text-align: center;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    .document-id {
      font-family: 'Courier New', monospace;
      font-size: 9pt;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(documentName)}</h1>
    <div class="status">✓ ELECTRONICALLY SIGNED</div>
  </div>

  <div class="signature-section">
    <h2>Electronic Signature</h2>
    
    <div class="signature-image">
      <img src="${signatureData.signatureDataUrl}" alt="Electronic Signature" />
      <div style="margin-top: 10px; font-size: 10pt;">Electronically Signed</div>
    </div>

    <div class="signature-details">
      <h3>Signature Verification Details</h3>
      <div class="detail-row">
        <div class="detail-label">Date:</div>
        <div class="detail-value">${escapeHtml(signatureData.signedDate)}</div>
      </div>
      <div class="detail-row">
        <div class="detail-label">Time:</div>
        <div class="detail-value">${escapeHtml(signatureData.signedTime)}</div>
      </div>
      <div class="detail-row">
        <div class="detail-label">IP Address:</div>
        <div class="detail-value">${escapeHtml(signatureData.ipAddress)}</div>
      </div>
      <div class="detail-row">
        <div class="detail-label">Timestamp:</div>
        <div class="detail-value">${signatureData.timestamp.toISOString()}</div>
      </div>
    </div>

    <div class="certification">
      <strong>CERTIFICATION:</strong><br>
      This document has been electronically signed. The signature, date, time, and 
      IP address have been permanently affixed to this document and cannot be altered.
    </div>
  </div>

  <div class="footer">
    <div class="document-id">Document ID: ${documentId}</div>
    <div>Signed: ${signedDate}</div>
    <div>System: Legal Services Document Workflow System</div>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF
  const signedPdfDataUrl = await htmlToPDF(htmlContent);
  
  return signedPdfDataUrl;
}

/**
 * Converts a data URL to a Blob for downloading
 * @param dataUrl - The data URL to convert
 * @param filename - The filename for the download
 */
export function downloadPDF(dataUrl: string, filename: string): void {
  // Ensure filename has .html extension for HTML-based documents
  const finalFilename = filename.endsWith('.html') || filename.endsWith('.pdf') 
    ? filename 
    : `${filename}.html`;
  
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = finalFilename;
  link.target = '_blank';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Validates if a string is a valid PDF or HTML data URL
 * @param dataUrl - The data URL to validate
 * @returns True if valid document data URL
 */
export function isValidPDFDataUrl(dataUrl: string): boolean {
  return dataUrl.startsWith('data:application/pdf;base64,') || 
         dataUrl.startsWith('data:text/html;base64,');
}

/**
 * Helper function to escape HTML special characters
 * @param text - Text to escape
 * @returns Escaped text
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Converts HTML content to PDF data URL using browser's print functionality
 * @param htmlContent - HTML content to convert
 * @returns Base64 encoded PDF data URL (HTML format for viewing)
 */
async function htmlToPDF(htmlContent: string): Promise<string> {
  return new Promise((resolve) => {
    // Create a blob URL for the HTML content that can be viewed in browser
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const blobUrl = URL.createObjectURL(blob);
    
    // For better compatibility, we'll return the HTML as a data URL
    // This allows the document to be viewed in the browser and printed as PDF
    const base64Content = btoa(unescape(encodeURIComponent(htmlContent)));
    const htmlDataUrl = `data:text/html;base64,${base64Content}`;
    
    resolve(htmlDataUrl);
  });
}
