/**
 * Document Generation and Signature Embedding Utility
 * 
 * This utility provides functions to:
 * 1. Generate text documents from content
 * 2. Embed electronic signatures with metadata (date, time, IP) into documents
 * 
 * Note: This is a simplified implementation that creates text-based documents.
 * For production PDF generation, consider integrating a server-side PDF library.
 */

import { SignatureData } from '@/components/DocumentSignature';

/**
 * Generates a text document from content
 * @param content - The text content to convert to document
 * @param documentName - Name of the document
 * @returns Base64 encoded text data URL
 */
export async function generatePDF(content: string, documentName: string): Promise<string> {
  // Create a formatted text document
  const documentContent = `
${'='.repeat(80)}
${documentName.toUpperCase()}
${'='.repeat(80)}

Generated: ${new Date().toLocaleString()}

${'-'.repeat(80)}
DOCUMENT CONTENT
${'-'.repeat(80)}

${content}

${'-'.repeat(80)}
SIGNATURE SECTION
${'-'.repeat(80)}

This document requires your electronic signature.
Please sign using the document workflow portal.


_____________________________________________
Signature


Document ID: DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}
Generated by: Legal Services Document Workflow System
`;

  // Convert to base64 data URL
  const base64Content = btoa(unescape(encodeURIComponent(documentContent)));
  const dataUrl = `data:text/plain;base64,${base64Content}`;
  
  return dataUrl;
}

/**
 * Embeds signature with metadata into a document
 * @param originalDocDataUrl - The original document as a data URL
 * @param signatureData - Signature data including image, date, time, and IP
 * @param documentName - Name of the document
 * @returns Base64 encoded signed document data URL
 */
export async function embedSignatureInPDF(
  originalDocDataUrl: string,
  signatureData: SignatureData,
  documentName: string
): Promise<string> {
  // Get the original content (decode from base64)
  let originalContent = '';
  if (originalDocDataUrl.startsWith('data:text/plain;base64,')) {
    const base64Content = originalDocDataUrl.split(',')[1];
    originalContent = atob(base64Content);
  }

  // Create signed document with embedded signature
  const documentId = `DOC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  
  const signedDocumentContent = `
${'='.repeat(80)}
${documentName.toUpperCase()} - SIGNED
${'='.repeat(80)}

${originalContent}

${'='.repeat(80)}
ELECTRONIC SIGNATURE
${'='.repeat(80)}

[Signature Image Data: ${signatureData.signatureDataUrl.substring(0, 50)}...]

_____________________________________________
Electronically Signed


╔════════════════════════════════════════════════════════════════════════════╗
║ SIGNATURE VERIFICATION DETAILS                                             ║
╠════════════════════════════════════════════════════════════════════════════╣
║ Date:           ${signatureData.signedDate.padEnd(56)}║
║ Time:           ${signatureData.signedTime.padEnd(56)}║
║ IP Address:     ${signatureData.ipAddress.padEnd(56)}║
║ Timestamp:      ${signatureData.timestamp.toISOString().padEnd(56)}║
╚════════════════════════════════════════════════════════════════════════════╝

CERTIFICATION:
This document has been electronically signed. The signature, date, time, and 
IP address have been permanently affixed to this document and cannot be altered.

${'-'.repeat(80)}
Document ID: ${documentId}
Generated: ${new Date().toISOString()}
System: Legal Services Document Workflow System
${'-'.repeat(80)}
`;

  // Convert to base64 data URL
  const base64Content = btoa(unescape(encodeURIComponent(signedDocumentContent)));
  const signedDataUrl = `data:text/plain;base64,${base64Content}`;
  
  return signedDataUrl;
}

/**
 * Converts a data URL to a Blob for downloading
 * @param dataUrl - The data URL to convert
 * @param filename - The filename for the download
 */
export function downloadPDF(dataUrl: string, filename: string): void {
  const link = document.createElement('a');
  link.href = dataUrl;
  
  // Determine file extension based on data URL type
  let finalFilename = filename;
  if (dataUrl.startsWith('data:text/plain')) {
    finalFilename = filename.endsWith('.txt') ? filename : `${filename}.txt`;
  } else if (dataUrl.startsWith('data:application/pdf')) {
    finalFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  } else {
    // Default to .txt for text documents
    finalFilename = filename.includes('.') ? filename : `${filename}.txt`;
  }
  
  link.download = finalFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Validates if a string is a valid document data URL
 * @param dataUrl - The data URL to validate
 * @returns True if valid document data URL
 */
export function isValidPDFDataUrl(dataUrl: string): boolean {
  return dataUrl.startsWith('data:application/pdf;base64,') || 
         dataUrl.startsWith('data:text/plain;base64,');
}
